# Generated by Django 3.1.3 on 2021-02-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210218_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
