# Generated by Django 3.1.3 on 2021-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210218_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
