# Generated by Django 3.1.3 on 2021-02-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20210223_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
